[input_parameters]
length = 0.01
amplitude_perturbation_x = 1e-7
wavenumber_electrons = 8
grid_points_per_Debye_length = 2
vth_electrons_over_c = 0.05
ion_temperature_over_electron_temperature = 0.01
timestep_over_spatialstep_times_c = 1.0
electron_drift_speed = 100000000.0
velocity_plus_minus_electrons = true
print_info = true
external_electric_field_amplitude = 0
external_electric_field_wavenumber = 0
electron_charge_over_elementary_charge = -1
ion_charge_over_elementary_charge = 1
ion_mass_over_proton_mass = 1

[solver_parameters]
field_solver = 0
number_grid_points = 100
number_pseudoelectrons = 3000
total_steps = 1000
