[input_parameters]
length = 0.01
amplitude_perturbation_x = 0.0000005
wavenumber_electrons_x = 1
grid_points_per_Debye_length = 0.50265482457
vth_electrons_over_c_x = 0.05
ion_temperature_over_electron_temperature = 0.01
timestep_over_spatialstep_times_c = 4.5
electron_drift_speed_x = 6e7
velocity_plus_minus_electrons_x = true
print_info = true
external_electric_field_amplitude = 0
external_electric_field_wavenumber = 0
electron_charge_over_elementary_charge = -1
ion_charge_over_elementary_charge = 1
ion_mass_over_proton_mass = 1
relativistic = false
tolerance_Picard_iterations_implicit_CN = 1e-10
filter_passes = 5
filter_alpha =  0.5
filter_strides = [1, 2, 4]

[solver_parameters]
field_solver = 0                 # Algorithm to solve E and B fields - 0: Curl_EB, 1: Gauss_1D_FFT, 2: Gauss_1D_Cartesian, 3: Poisson_1D_FFT,
time_evolution_algorithm = 0     # Algorithm to evolve particles in time - 0: Boris, 1: Implicit_Crank Nicholson
number_grid_points = 70          # Number of grid points
number_pseudoelectrons = 3500    # Number of pseudoelectrons
total_steps = 1100               # Total number of time steps
max_number_of_Picard_iterations_implicit_CN = 20
number_of_particle_substeps_implicit_CN = 2